<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDaIM0xW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDaIM0xW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDaIM0xW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDaIM0xW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDaIM0xW\App_KernelDevDebugContainer([
    'container.build_hash' => 'DaIM0xW',
    'container.build_id' => 'ff6536cf',
    'container.build_time' => 1597844459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDaIM0xW');
