<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKoqJx7O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKoqJx7O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKoqJx7O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKoqJx7O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKoqJx7O\App_KernelDevDebugContainer([
    'container.build_hash' => 'KoqJx7O',
    'container.build_id' => '2c7503aa',
    'container.build_time' => 1597842299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKoqJx7O');
